name: Calculate Next Release Number v1

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  call-calculate-next-release-number-workflow:
    name: Calculate Next Release Number
    uses: cangulo-actions/workflows/.github/workflows/calculate-next-release-number.yml@v0.0.1
    with:
      releaseSettingsPath: ./cicd/releaseSettings.json
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}