name: Calculate Next Release Number v1

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-conventional-commits:
    name: Calculate Next Release Number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calculating Next Release Version
        uses: cangulo-actions/cangulo.nuke.releasecreator@v0.0.1
        with:
          releaseSettingsPath: ./cicd/releaseSettings.json
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyCalculateReleaseNumber: true
